# Generated by Django 3.2.5 on 2021-09-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regions',
            fields=[
                ('region_id', models.IntegerField(default=50, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=100)),
                ('region_lat', models.FloatField(blank=True, null=True)),
                ('region_long', models.FloatField(blank=True, null=True)),
                ('region_area', models.FloatField(blank=True, null=True)),
                ('region_code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='retailers',
            fields=[
                ('retailer_id', models.IntegerField(default=150, primary_key=True, serialize=False)),
                ('retailer_name', models.CharField(max_length=100)),
                ('store_type', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'retailers',
            },
        ),
    ]
