# Generated by Django 3.2.5 on 2021-09-17 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='municipalities',
            fields=[
                ('municipality_id', models.IntegerField(default=3000, primary_key=True, serialize=False)),
                ('municipality_code', models.CharField(max_length=10)),
                ('municipality_name', models.CharField(max_length=100)),
                ('municipality_area', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('number_of_cars', models.IntegerField(blank=True, null=True)),
                ('avg_income', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'municipalities',
            },
        ),
        migrations.CreateModel(
            name='regions',
            fields=[
                ('region_id', models.IntegerField(default=50, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=100)),
                ('region_lat', models.FloatField(blank=True, null=True)),
                ('region_long', models.FloatField(blank=True, null=True)),
                ('region_area', models.FloatField(blank=True, null=True)),
                ('region_code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='retailers',
            fields=[
                ('retailer_id', models.IntegerField(default=150, primary_key=True, serialize=False)),
                ('retailer_name', models.CharField(max_length=100)),
                ('store_type', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'retailers',
            },
        ),
        migrations.CreateModel(
            name='stores',
            fields=[
                ('store_id', models.IntegerField(default=99999, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100)),
                ('store_address', models.CharField(max_length=300)),
                ('store_lat', models.FloatField(blank=True, null=True)),
                ('store_long', models.FloatField(blank=True, null=True)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeLocationsApp.municipalities')),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeLocationsApp.retailers')),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.AddField(
            model_name='municipalities',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeLocationsApp.regions'),
        ),
    ]
