# Generated by Django 3.2.5 on 2021-09-16 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeLocationsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='municipalities',
            fields=[
                ('municipality_id', models.IntegerField(default=3000, primary_key=True, serialize=False)),
                ('municipality_code', models.CharField(max_length=10)),
                ('municipality_name', models.CharField(max_length=100)),
                ('municipality_area', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('number_of_cars', models.IntegerField(blank=True, null=True)),
                ('avg_income', models.IntegerField(blank=True, null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeLocationsApp.regions')),
            ],
            options={
                'db_table': 'municipalities',
            },
        ),
    ]
